### ISSUE TITLE
Demon NOK

### ISSUE THREAD

**Issue by kouloubike** [Jeremie-C/plugin-MerossIOT#10]
Bonjour jeremie-C

Je te contact car j'ai une erreur avec le plug-in 
J'ai le demon qui demarre puis  s'arrete cela en boucle 
J'ai la dernière version de ton plug in et je suis sur debian buster 
J'ai vérifié j'ai bien la dernière version de python 3.7.3

`[2020-05-14 18:41:12][ERROR] : Impossible de stopper le démon meross, tuons le
[2020-05-14 18:41:13][ERROR] : Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consécutivement
[2020-05-14 18:41:13][INFO] : Lancement démon meross : /usr/bin/python3 /var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py --muser "xxx" --mpswd "xxx" --mupdp 20 --callback http://127.0.0.1:80/plugins/MerossIOT/core/php/jeeMerossIOT.php --apikey 7CNqpU06CQLKRJw6tctVEejmngSBCgA6 --loglevel debug --pid /tmp/jeedom/MerossIOT/daemon.pid --socket /tmp/jeedom/MerossIOT/daemon.sock
[2020-05-14 18:41:14][INFO][root](MainThread) : Start MerossIOTd
[2020-05-14 18:41:14][INFO][root](MainThread) : Log level : debug
[2020-05-14 18:41:14][INFO][root](MainThread) : Socket : /tmp/jeedom/MerossIOT/daemon.sock
[2020-05-14 18:41:14][INFO][root](MainThread) : PID file : /tmp/jeedom/MerossIOT/daemon.pid
[2020-05-14 18:41:14][INFO][root](MainThread) : Apikey : 7CNqpU06CQLKRJw6tctVEejmngSBCgA6
[2020-05-14 18:41:14][INFO][root](MainThread) : Update Power : 20
[2020-05-14 18:41:14][INFO][root](MainThread) : Callback : http://127.0.0.1:80/plugins/MerossIOT/core/php/jeeMerossIOT.php
[2020-05-14 18:41:14][INFO][root](MainThread) : Python version : 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0]
[2020-05-14 18:41:14][DEBUG][root](MainThread) : Ecriture du PID 11626 dans /tmp/jeedom/MerossIOT/daemon.pid
[2020-05-14 18:41:14][DEBUG][root](MainThread) : Envoi un test à jeedom
[2020-05-14 18:41:14][DEBUG][root](MainThread) : Envoie à jeedom :  {'action': 'test'}
[2020-05-14 18:41:14][DEBUG] : Array (     [action] => test )
[2020-05-14 18:41:14][DEBUG][root](MainThread) : Réponse de jeedom :  {'success': True}
[2020-05-14 18:41:14][INFO][root](MainThread) : Démarrage Meross Manager
[2020-05-14 18:41:16][INFO] : Démon meross lancé.
2020-05-14 18:41:19,913 - meross.manager - DEBUG - Starting manager
[2020-05-14 18:41:19][DEBUG][meross.manager](MainThread) : Starting manager
2020-05-14 18:41:19,914 - meross.connection - INFO - Initializing the MQTT connection...
[2020-05-14 18:41:19][INFO][meross.connection](MainThread) : Initializing the MQTT connection...
[2020-05-14 18:41:51][DEBUG] : Synchronisation des équipements depuis le Cloud Meross
[2020-05-14 18:41:51][DEBUG] : callMeross syncMeross
Traceback (most recent call last):
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 472, in <module>
mm.start()
File "/usr/local/lib/python3.7/dist-packages/meross_iot/manager.py", line 55, in start
self._cloud_client.connect()
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/client.py", line 147, in connect
self._mqtt_client.connect(self._domain, self._port, keepalive=30)
File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 937, in connect
return self.reconnect()
File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
sock = self._create_socket_connection()
File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
File "/usr/lib/python3.7/socket.py", line 727, in create_connection
raise err
File "/usr/lib/python3.7/socket.py", line 716, in create_connection
sock.connect(sa)
socket.timeout: timed out
[2020-05-14 18:42:20][DEBUG] : result callMeross
[2020-05-14 18:42:20][DEBUG] : syncMeross: synchronisation terminée.`

**Comment by Jeremie-C** [comment]
Bonjour,

Il apparait que la librairie n'arrive pas à créer le socket : socket.timeout dans le log.
Celà peut venir d'une latence réseau, d'un problème de DNS, que le cloud soit hors ligne (très peu probable), ....

Merci de vérifier que votre jeedom récupère bien l'adresse du cloud meross :
nslookup eu-iot.meross.com
nslookup us-iot.meross.com
nslookup iot.meross.com
