### ISSUE TITLE
Le Daemon ne se lance plus, trop d'itentification ?

### ISSUE THREAD

**Issue by flopp26** [Jeremie-C/plugin-MerossIOT#14]
Bonjour et tout d'abord merci pour ce plugin jeedom.

Depuis plusieurs jours, mon daemon ne se lance plus et j'ai cette erreur dans les logs
Merci d'avance

`meross_iot.api.TooManyTokensException: You have issued too many tokens without logging out.`

`File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 469, in <module>
mm = MerossManager.from_email_and_password(args.muser, args.mpswd)
File "/usr/local/lib/python3.5/dist-packages/meross_iot/manager.py", line 21, in from_email_and_password
cloud_creds = MerossHttpClient.login(email=meross_email, password=meross_password)
File "/usr/local/lib/python3.5/dist-packages/meross_iot/api.py", line 48, in login
response_data = cls._authenticated_post(_LOGIN_URL, params_data=data)
File "/usr/local/lib/python3.5/dist-packages/meross_iot/api.py", line 112, in _authenticated_post
raise TooManyTokensException("You have issued too many tokens without logging out.")
meross_iot.api.TooManyTokensException: You have issued too many tokens without logging out.
[2020-06-02 15:35:15][ERROR] : Impossible de lancer le démon meross, vérifiez le log
[2020-06-02 15:40:03][ERROR] : Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consécutivement
Traceback (most recent call last):
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 469, in <module>
mm = MerossManager.from_email_and_password(args.muser, args.mpswd)
File "/usr/local/lib/python3.5/dist-packages/meross_iot/manager.py", line 21, in from_email_and_password
cloud_creds = MerossHttpClient.login(email=meross_email, password=meross_password)
File "/usr/local/lib/python3.5/dist-packages/meross_iot/api.py", line 48, in login
response_data = cls._authenticated_post(_LOGIN_URL, params_data=data)
File "/usr/local/lib/python3.5/dist-packages/meross_iot/api.py", line 112, in _authenticated_post
raise TooManyTokensException("You have issued too many tokens without logging out.")
meross_iot.api.TooManyTokensException: You have issued too many tokens without logging out.`

**Comment by Jeremie-C** [comment]
Bonjour,

D'après le message d'erreur, vous avez trop de connexion ouverte en même temps ou non fermée.
Mon plugin ouvre une seul et unique connexion et la ferme a chaque arrêt du démon.

Peut être avez vous l'app meross sur des téléphones, tablettes, ...

Je n'ai jamais eu ce message avec l'app sur un téléphone + le plugin sur 2 Jeedom avec le même compte.

A mon avis, le plugin n'est pas en cause.

**Comment by flopp26** [comment]
Merci pour la réponse.

Pourtant je n'ai installé l'app que sur mon téléphone et sur 1 seul jeedom.
J'ai essayé d'ouvrir l'app du tél et de me déconnecter, rien ne change coté jeedom
J'ai essayé de désactiver le plugin et de le réactiver.
J'ai essayé de changer mon mot de passe et pareil.
Je ne sais pas quoi essayer d'autres
