### ISSUE TITLE
A timeout occurred while waiting for the ACK: 10

### ISSUE THREAD

**Issue by Githubjeedomuser** [Jeremie-C/plugin-MerossIOT#16]
Bonjour,
l'installation du plugin s'effectue correctement sur Jeedom Smart. Cependant aucun équipement ne s'affiche même après plusieures synchronisations. Je posséde 5 prises Meross mss310FR et 3 mss310EU qui fonctionnent avec l'appli Meross et aussi avec IFTTT.
J'ai une erreur Timeout dans le log MerossIOT.
Merci

**Santé Jeedom Smart :**
Système à jour | OK | Cron actif | OK
-- | -- | -- | --
Scénario actif | OK | Démarré | OK 2016-11-03 18:18:02
Date système (dernière heure enregistrée) | OK 2020-07-19 19:55:31 (2020-07-19 19:38:02) | Droits sudo | OK
Version Jeedom | 4.0.60 | Version PHP | 7.0.27-0+deb9u1
Apache | 13 | Version OS | Linux jeedom 3.14.79-94 #1 SMP PREEMPT Mon Nov 21 17:13:27 BRST 2016 aarch64 GNU/Linux  [9.4]
Version database | 10.1.26-MariaDB-0+deb9u1 | Espace disque libre | 56 %
Espace disque libre tmp | 100 % | Mémoire disponible | 79 % (Total 1717 Mo)
Mémoire suffisante | 0 | Erreur I/O | 0
Swap disponible | 100 % (Total 256 Mo) | Swapiness | 10 %
Charge | 0.27 - 0.31 - 0.3 | Configuration réseau interne | OK
Configuration réseau externe | OK | Persistance du cache | OK (2020-07-19 19:30:03)
Apache private tmp | OK
Plugins | OK |  

**Santé MerossIOT :**
Dépendances | OK
Configuration démon | OK
Statut démon | OK

**Log MerossIOT :**
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 123, in handle
    response['result'] = response['result'](*args)
  File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 324, in syncMeross
    d = self.syncOneMeross(device)
  File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 210, in syncOneMeross
    data = device.get_sys_data()
  File "/usr/local/lib/python3.5/dist-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
    return self.execute_command("GET", ALL, {}, online_check=False)
  File "/usr/local/lib/python3.5/dist-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/meross_iot/cloud/client.py", line 301, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
----------------------------------------
Exception happened during processing of request from b''

**Log MerossIOT_update :**
Installation des dépendances
Ign:2 http://ftp.debian.org/debian stretch InRelease
Hit:3 http://security.debian.org stretch/updates InRelease
Hit:4 http://ftp.debian.org/debian stretch-updates InRelease
Hit:5 http://ftp.debian.org/debian stretch-backports InRelease
Hit:6 http://ftp.debian.org/debian stretch-proposed-updates InRelease
Hit:7 http://ftp.debian.org/debian stretch Release
Get:1 https://repo.jeedom.com/odroid stable InRelease [1640 B]
Hit:8 http://www.deb-multimedia.org stretch InRelease
Hit:9 https://oph.mdrjr.net/meveric all InRelease
Hit:10 https://oph.mdrjr.net/meveric stretch InRelease
Fetched 1640 B in 3s (517 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.5.3-1).
The following packages were automatically installed and are no longer required:
  libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libpng12-0
  libqdbm14 libvpx1 linux-image-3.14.29+ linux-image-arm64-odroid-c2
  python-lockfile u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 199 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (9.0.1-2+deb9u1).
The following packages were automatically installed and are no longer required:
  libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libpng12-0
  libqdbm14 libvpx1 linux-image-3.14.29+ linux-image-arm64-odroid-c2
  python-lockfile u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 199 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-requests is already the newest version (2.12.4-1).
The following packages were automatically installed and are no longer required:
  libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libpng12-0
  libqdbm14 libvpx1 linux-image-3.14.29+ linux-image-arm64-odroid-c2
  python-lockfile u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 199 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-setuptools is already the newest version (33.1.1-1).
The following packages were automatically installed and are no longer required:
  libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libpng12-0
  libqdbm14 libvpx1 linux-image-3.14.29+ linux-image-arm64-odroid-c2
  python-lockfile u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 199 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-dev is already the newest version (3.5.3-1).
The following packages were automatically installed and are no longer required:
  libmemcached11 libmemcachedutil2 libmysqlclient18 libonig2 libpng12-0
  libqdbm14 libvpx1 linux-image-3.14.29+ linux-image-arm64-odroid-c2
  python-lockfile u-boot-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 199 not upgraded.
Requirement already satisfied: meross_iot==0.3.4.6 in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: paho-mqtt>=1.3.1 in /usr/local/lib/python3.5/dist-packages (from meross_iot==0.3.4.6)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.5/dist-packages (from meross_iot==0.3.4.6)
Requirement already satisfied: requests>=2.19.1 in /usr/local/lib/python3.5/dist-packages (from meross_iot==0.3.4.6)
Requirement already satisfied: six>=1.7.0 in /usr/lib/python3/dist-packages (from retrying>=1.3.3->meross_iot==0.3.4.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests>=2.19.1->meross_iot==0.3.4.6)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests>=2.19.1->meross_iot==0.3.4.6)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests>=2.19.1->meross_iot==0.3.4.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests>=2.19.1->meross_iot==0.3.4.6)
Installation des dépendances terminée !

**Comment by Githubjeedomuser** [comment]
Donc il n'y a pas de solutions ou bien ce n'est pas un problème étant donné que personne ne répond.
