### ISSUE TITLE
Impossible de lancer demon : PI 4 Buster

### ISSUE THREAD

**Issue by ybuffin** [Jeremie-C/plugin-MerossIOT#18]
Bonjour,

je viens de changer mon Raspberry pi3  par un pi4 et je ne parviens plus a lancer le demon depuis.
J'ai désinstallé et réinstallé le plugin mais rien n'y fait. Je penses que c'est un soucis de python mais ça fait 1 journée que je regardes et je ne trouve pas

pi3 : 
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
pi@JeedomPi:~ $ python --version 
Python 2.7.13
pi@JeedomPi:~ $ python3 --version
Python 3.5.3

Pi4 
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
pi@JeedomPi4:~ $ python --version
Python 2.7.16
pi@JeedomPi4:~ $ python3 --version
Python 3.7.3
pi@JeedomPi4:~ $ 

Ci dessous les logs d'erreur : 
[2020-10-20 12:01:04][ERROR] : Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consécutivement
Traceback (most recent call last):
  File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 467, in <module>
    mm = MerossManager.from_email_and_password(args.muser, args.mpswd)
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/manager.py", line 25, in from_email_and_password
    auto_reconnect=auto_reconnect)
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/manager.py", line 39, in __init__
    auto_reconnect=auto_reconnect)
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/client.py", line 113, in __init__
    self._mqtt_client = mqtt.Client(client_id=self._client_id,
AttributeError: module 'paho.mqtt.client' has no attribute 'Client'
[2020-10-20 12:01:21][ERROR] : Impossible de lancer le démon meross, vérifiez le log

les info des dépendances :
Installation des dépendances
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 http://phoscon.de/apt/deconz buster InRelease
Hit:4 https://deb.nodesource.com/node_12.x buster InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-requests is already the newest version (2.21.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-setuptools is already the newest version (40.8.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3-dev is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: meross_iot==0.3.4.6 in /usr/local/lib/python3.7/dist-packages (0.3.4.6)
Requirement already satisfied: requests>=2.19.1 in /usr/lib/python3/dist-packages (from meross_iot==0.3.4.6) (2.21.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from meross_iot==0.3.4.6) (1.3.3)
Requirement already satisfied: paho-mqtt>=1.3.1 in /usr/local/lib/python3.7/dist-packages (from meross_iot==0.3.4.6) (1.5.1)
Installation des dépendances terminée !

Merci par avance pour ton retour

**Comment by Jeremie-C** [comment]
Bonjour,

je suis RPI4 à la maison et cela fonctionne.
Je vais monter un RPI4 de test pour voir si le soucis ne vient pas de la
version 1.5.1 de paho-mqtt qui chez moi est en 1.4.2

**Comment by ybuffin** [comment]
Merci pour ton retour rapide.

Il fallait que je demande mais je viens de trouver en analysant un peu les différentes classes python utilisées.
Au final me manquait simplement les classes de la librairie paho-mqtt (les fichiers étaient vides dans le dossier /usr/local/lib/python3.7/dist-packages/paho ) d’où l'erreur, l'objet mqtt n'a pas d'attribut Client !

je l'aie donc réinstallé : sudo pip paho-mqtt (déployé dans dossier /usr/local/lib/python2.7)
et j'ai supprimé le dossier avec les fichiers vides avec : sudo pip3 uninstal paho-mqtt 
je viens de regarder à nouveau, le dossier est de nouveau présent avec les bons fichiers cette fois dans le dossier /usr/local/lib/python3.7/dist-packages/paho

Reproduction : Déploiement de rasberry OS pi4 directement sur un sdd (depuis la procédure actuelle) 

Du coup le demon refonctionne,

**Comment by Jeremie-C** [comment]
Parfait.
Sujet clos donc.
Bonne utilisation !!
