### ISSUE TITLE
Deamon Not started 

### ISSUE THREAD

**Issue by benoitfl** [Jeremie-C/plugin-MerossIOT#19]
Bonjour, même issue que certains, cependant je pense avoir toutes les librairies installée, le mot de passe  est correcte et le refresh rate est à 60.

RPI pi 4. 

Je pensais avoir un soucis sur mon PI j'ai donc réinstallé l'ensemble dans le doute sans succès.

[2020-10-25 15:59:22][ERROR] : Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consécutivement
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='iot.meross.com', port=443): Max retries exceeded with url: /v1/Auth/Login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 467, in <module>
    mm = MerossManager.from_email_and_password(args.muser, args.mpswd)
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/manager.py", line 21, in from_email_and_password
    cloud_creds = MerossHttpClient.login(email=meross_email, password=meross_password)
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/api.py", line 48, in login
    response_data = cls._authenticated_post(_LOGIN_URL, params_data=data)
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/api.py", line 91, in _authenticated_post
    r = requests.post(url, data=payload, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='iot.meross.com', port=443): Max retries exceeded with url: /v1/Auth/Login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

Merci de votre aide !

**Comment by Jeremie-C** [comment]
Bonjour,

Le message d'erreur nous dit qu'il ne peut vérifier le certificat SSL de
iot.meross.com

Soit le certificat est HS, soit la librairie dépendante échoué a le
vérifier.
Je regarde ce que je peut trouver concernant cette librairie.

Merci.
