### ISSUE TITLE
Impossible de lancer le démon meross

### ISSUE THREAD

**Issue by Its-MyName** [Jeremie-C/plugin-MerossIOT#20]
Bonjour,

Nouveau dans Jeedom et premier plugin que j’installe.  J'ai suivi le tutoriel présent [ici](https://www.objetsconnectes.be/2020/01/31/jeedom-plugin-meross/#Installer_le_plugin_officiel_Jeedom_Meross_IOT_de_Jeremie-C).

Je dispose uniquement de prises Meross MS310 parfaitement utilisable via leur application.

J'ai par contre cette erreur en essayant d'utiliser leplugin (login/mdp configuré et vérifié) : 

> Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/meross_iot/api.py", line 102, in _authenticated_post
> result_code = ErrorCodes(code)
> File "/usr/lib/python3.5/enum.py", line 241, in __call__
> return cls.__new__(cls, value)
> File "/usr/lib/python3.5/enum.py", line 476, in __new__
> raise ValueError("%r is not a valid %s" % (value, cls.__name__))
> ValueError: 1004 is not a valid ErrorCodes
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 467, in <module>
> mm = MerossManager.from_email_and_password(args.muser, args.mpswd)
> File "/usr/local/lib/python3.5/dist-packages/meross_iot/manager.py", line 21, in from_email_and_password
> cloud_creds = MerossHttpClient.login(email=meross_email, password=meross_password)
> File "/usr/local/lib/python3.5/dist-packages/meross_iot/api.py", line 48, in login
> response_data = cls._authenticated_post(_LOGIN_URL, params_data=data)
> File "/usr/local/lib/python3.5/dist-packages/meross_iot/api.py", line 121, in _authenticated_post
> raise AuthenticatedPostException("Failed request to API. Response was: %s" % str(jsondata))
> meross_iot.api.AuthenticatedPostException: Failed request to API. Response was: {'apiStatus': 1004, 'sysStatus': 0, 'timeStamp': '2020-11-15 14:35:06', 'data': None, 'info': 'A'}
> [2020-11-15 15:35:25][ERROR] : Impossible de lancer le démon meross, vérifiez le log

Toute aide serait appréciée :-)
Merci d'avance

Jeedom Version : 4.0.61

**Comment by lstep** [comment]
Même problème, juste après installation, et renseignement des email et pass. Je pense que l'API chez Meross a changé. Est-ce qu'il y a une doc officielle de cette API quelque part ?

**Comment by yozart** [comment]
Même probleme pour moi! Y a t'il un fix de prévu ?
Jeremie ? please ?
