### ISSUE TITLE
A timeout occurred while waiting for the ACK: 10

### ISSUE THREAD

**Issue by Githubjeedomuser** [Jeremie-C/plugin-MerossIOT#24]
Bonjour, tout fonctionnait bien jusqu'à maintenant. Depuis ce matin plus aucun équipement ne fonctionne.
Si je clique sur une commande j'obtiens ceci :
Erreur exécution de la commande [Habitation][Divers][Refresh] : Le nom de l'équipement ne peut pas être vide : MerossIOT Object ( [id:protected] => [name:protected] => [logicalId:protected] => [generic_type:protected] => [object_id:protected] => [eqType_name:protected] => MerossIOT [isVisible:protected] => 0 [isEnable:protected] => 0 [configuration:protected] => Array ( [online] => 0 ) [timeout:protected] => 0 [category:protected] => [display:protected] => [order:protected] => 9999 [comment:protected] => [tags:protected] => [_debug:protected] => [_object:protected] => [_needRefreshWidget:protected] => [_timeoutUpdated:protected] => [_batteryUpdated:protected] => [_changed:protected] => 1 ) 

Log Meross :
Exception happened during processing of request from
Traceback (most recent call last):
File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
self.handle()
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 123, in handle
response['result'] = response['result'](*args)
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 332, in syncDevice
d = self.syncOneMeross(device)
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 210, in syncOneMeross
data = device.get_sys_data()
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 119, in get_sys_data
return self.execute_command("GET", ALL, {}, online_check=False)
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 116, in execute_command
return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/client.py", line 301, in execute_cmd
raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10

**Comment by BHMath** [comment]
Il faut mettre à jour la version de la dépendance meross_iot en v4 et refaire le plugin. Est-ce envisageable ?

à voir avec l'auteur.
