### ISSUE TITLE
Impossible de synchroniser les prises

### ISSUE THREAD

**Issue by BHMath** [Jeremie-C/plugin-MerossIOT#25]
Bonjour,

J'ai 3 prise sur mon compte Meross mais lorsque je fait sync rien n'apparait dans ma liste ni dans les logs.

Pouvez-vous m'aider svp !

**Comment by BHMath** [comment]
Ok j'ai compris il faut mettre à jour la version de la dépendance meross_iot en v4 et refaire le plugin. Est-ce envisageable ?

**Comment by piere07** [comment]
Bonsoir,

J'ai un problème similaire, mais, seulement, depuis une semaine. Mes 6 prises Meross se sont mises à ne plus répondre puis ont carrément disparues.
Dans le fichier de log, il y a ceci :
[2021-09-14 20:11:51][DEBUG][meross.connection](Thread-5) : Executing message-id c90f20c53f3bd3aa759952bb76bdf5c6, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
2021-09-14 20:11:51,373 - meross.connection - DEBUG - Waiting for response to message-id c90f20c53f3bd3aa759952bb76bdf5c6
[2021-09-14 20:11:51][DEBUG][meross.connection](Thread-5) : Waiting for response to message-id c90f20c53f3bd3aa759952bb76bdf5c6
2021-09-14 20:13:31,377 - meross.connection - DEBUG - Executing message-id 9623036b59c8f2309e05936a69cb17cb, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
[2021-09-14 20:13:31][DEBUG][meross.connection](Thread-5) : Executing message-id 9623036b59c8f2309e05936a69cb17cb, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
2021-09-14 20:13:31,378 - meross.connection - DEBUG - Waiting for response to message-id 9623036b59c8f2309e05936a69cb17cb
[2021-09-14 20:13:31][DEBUG][meross.connection](Thread-5) : Waiting for response to message-id 9623036b59c8f2309e05936a69cb17cb
2021-09-14 20:15:11,382 - meross.connection - DEBUG - Executing message-id 23d1818d6dea85f1c1282086b03329a0, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
[2021-09-14 20:15:11][DEBUG][meross.connection](Thread-5) : Executing message-id 23d1818d6dea85f1c1282086b03329a0, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
2021-09-14 20:15:11,385 - meross.connection - DEBUG - Waiting for response to message-id 23d1818d6dea85f1c1282086b03329a0
[2021-09-14 20:15:11][DEBUG][meross.connection](Thread-5) : Waiting for response to message-id 23d1818d6dea85f1c1282086b03329a0
2021-09-14 20:16:51,390 - meross.connection - DEBUG - Executing message-id dc3a6664b44506bd619ea910bcce168b, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
[2021-09-14 20:16:51][DEBUG][meross.connection](Thread-5) : Executing message-id dc3a6664b44506bd619ea910bcce168b, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
2021-09-14 20:16:51,390 - meross.connection - DEBUG - Waiting for response to message-id dc3a6664b44506bd619ea910bcce168b
[2021-09-14 20:16:51][DEBUG][meross.connection](Thread-5) : Waiting for response to message-id dc3a6664b44506bd619ea910bcce168b
2021-09-14 20:18:31,399 - meross.connection - DEBUG - Executing message-id 4f8f14943ff0b85b2b1946731e2e8095, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
[2021-09-14 20:18:31][DEBUG][meross.connection](Thread-5) : Executing message-id 4f8f14943ff0b85b2b1946731e2e8095, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
2021-09-14 20:18:31,400 - meross.connection - DEBUG - Waiting for response to message-id 4f8f14943ff0b85b2b1946731e2e8095
[2021-09-14 20:18:31][DEBUG][meross.connection](Thread-5) : Waiting for response to message-id 4f8f14943ff0b85b2b1946731e2e8095
[2021-09-14 20:20:03][DEBUG] : Mise à jour des consommations des équipements depuis le Cloud Meross
[2021-09-14 20:20:03][DEBUG] : callMeross syncMerossConso 
[2021-09-14 20:20:03][DEBUG][root](Thread-4) : Message received in socket
[2021-09-14 20:20:03][DEBUG][root](Thread-4) : {'action': 'syncMerossConso', 'args': ''}
2021-09-14 20:20:03,278 - meross.connection - DEBUG - Executing message-id f6fda28c58ef9523bfe8af7bad474a08, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
[2021-09-14 20:20:03][DEBUG][meross.connection](Thread-4) : Executing message-id f6fda28c58ef9523bfe8af7bad474a08, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
2021-09-14 20:20:03,278 - meross.connection - DEBUG - Waiting for response to message-id f6fda28c58ef9523bfe8af7bad474a08
[2021-09-14 20:20:03][DEBUG][meross.connection](Thread-4) : Waiting for response to message-id f6fda28c58ef9523bfe8af7bad474a08
2021-09-14 20:20:11,403 - meross.connection - DEBUG - Executing message-id 4d3878440b87943378a3a9986079831c, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
[2021-09-14 20:20:11][DEBUG][meross.connection](Thread-5) : Executing message-id 4d3878440b87943378a3a9986079831c, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
2021-09-14 20:20:11,404 - meross.connection - DEBUG - Waiting for response to message-id 4d3878440b87943378a3a9986079831c
[2021-09-14 20:20:11][DEBUG][meross.connection](Thread-5) : Waiting for response to message-id 4d3878440b87943378a3a9986079831c
[2021-09-14 20:20:13][DEBUG] : result callMeross 
[2021-09-14 20:20:13][DEBUG] : Mise à jour des consommations terminées.
2021-09-14 20:21:51,410 - meross.connection - DEBUG - Executing message-id a2267e7b11f85bdffd26afb1b547a045, GET on Appliance.System.Ability command for device 20062823308221251h4748e1e920484c
----------------------------------------
Exception happened during processing of request from 
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 123, in handle
    response['result'] = response['result'](*args)
  File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 341, in syncMerossConso
    if device.online and device.supports_consumption_reading():
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 152, in supports_consumption_reading
    return CONSUMPTIONX in self.get_abilities()
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 124, in get_abilities
    self._abilities = self.execute_command("GET", ABILITY, {})['ability']
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 116, in execute_command
    return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/client.py", line 301, in execute_cmd
    raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10

Pourriez-vous me dire de quel côté il faudrait chercher pour résoude ce problème ?

Merci par avance !! ;-)

**Comment by Michel57189** [comment]
Bonjour 

Même problème 

Et je pense que tous les utilisateurs du plugin Merossiot sous jeedom sont dans le même cas. 

Si @Jeremie-C pouvait simplement nous dire si une maintenance sera réalisée ou pas. Cela nous permettrait simplement de savoir à quoi nous en tenir 

Merci d avance

**Comment by Krankhore** [comment]
Pour info,  je n'ai pour l'instant aucun problème, la synchro fonctionne, les remontés de mes 8 prises sont correctes.
La version du plugin date du 20 juin 2020 et c'est apparemment la dernière  je suis en jeedom 4.1.25 et debian version 10.

**Comment by Michel57189** [comment]
Bonjour @Krankhore 

Très étonné de ton post car sur la communauté jeedom les utilisateurs qui remontent que leur plugin est KO sont nombreux 

Et d autant plus étonné parce que j ai la même version de plugin que toi et aussi sous debian10

**Comment by BHMath** [comment]
J'ai l'impression que ça dépend du firmware des prises

Le lun. 20 sept. 2021 à 11:33, Michel57189 ***@***.***> a
écrit :

**Comment by Notrede** [comment]
Pareil ici... cela ne fonctionne plus. Firmware a jour, jeedom et module Meross également...
:-(

**Comment by lolo5128** [comment]
Bonjour 
je n'ai plus aucune prise détecter sur jeedom même en refaisant une synchro cela ne change rien et je suis sou la version V4.1.27 de jeedom
Avez-vous une solution pour m'aider 
merci

**Comment by BHMath** [comment]
Ma solution fut de tout recréer dans wifilightv2...

**Comment by Krankhore** [comment]
Et comme je l'ai dit le 20 septembre dernier, chez moi tout fonctionne.
Mon jeedom est aussi en 4.1.27 et tourne sur une debian 10.10,  la version du plugin est 2020-06-22 01:06:52et les prises sont au dernier niveau de firmware de Meross.

Donc je dirais que le plugin est toujours bon pour communiquer avec le cloud Meross.
Mais je n'ai pas d'idée pour t'aider.C'est juste pour confirmer qu'il y a des environnements ou cela fonctione

**Comment by Notrede** [comment]
Chez moi également ca ne fonctionne pas...
Je pense qu'au contraire le plugin ne marche plus correctement suite a
changement sur le cloud Europe...
Possible qu'en fonction de la géographie, cela marche encore...

**Comment by PowerOfSun44** [comment]
même problème. j'ai tout supprimer et impossible de rajouter mes 4 prises connectées.
des nouvelles de @Jeremie-C  ?

**Comment by TwEnTyZz** [comment]
Bonjour à tous,
Toujours le même problème, malgré plusieurs réinstallations complètes du plugin ...
Est-ce que @Jeremie-C tu pourrais nous en dire plus, si toutefois tu as des infos ?
Merci :)

**Comment by impulsio** [comment]
Il semblerait que @Jeremie-C se base sur cette dépendance dont la version est 0.4.4.7 quand le plugin se base sur une version 0.3.4.6 => il faudrait donc mettre à jour cette version. Cela devrait aider...
