### ISSUE TITLE
Plantage démon

### ISSUE THREAD

**Issue by pletexier** [Jeremie-C/plugin-MerossIOT#5]
Bonjour,
J’ai 2 multiprises Meross mss425f avec un fonctionnement aléatoire.
Je suis sous Jeedom v4, installé sur un raspberry pi 3 avec Raspbian Buster.

Régulièrement, le démon se plante. Les boutons ne réagissent plus aux actions.
Au même moment, l'application Meross sur smartphone fonctionne correctement.

Si je redémarre le Démon ou Jeedom les commandes refonctionnent.

```

Dans les logs, j'ai ce genre de messages :
----------------------------------------
Exception happened during processing of request from
Traceback (most recent call last):
File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
self.handle()
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 104, in handle
response['result'] = response['result'](*args)
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 287, in syncDevice
d = self.syncOneMeross(device)
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 168, in syncOneMeross
data = device.get_sys_data()
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 129, in get_sys_data
return self.execute_command("GET", ALL, {})
[2020-03-23 19:00:14][ERROR] : Erreur exécution de la commande [Mult. Périphériques][Multi TV][Refresh] : Le nom de l'équipement ne peut pas être vide : MerossIOT Object (     [id:protected] =>      [name:protected] =>      [logicalId:protected] =>      [generic_type:protected] =>      [object_id:protected] =>      [eqType_name:protected] => MerossIOT     [eqReal_id:protected] =>      [isVisible:protected] => 0     [isEnable:protected] => 0     [configuration:protected] => Array         (             [online] => 0         )      [timeout:protected] => 0     [category:protected] =>      [display:protected] =>      [order:protected] => 9999     [comment:protected] =>      [tags:protected] =>      [_debug:protected] =>      [_object:protected] =>      [_needRefreshWidget:protected] =>      [_timeoutUpdated:protected] =>      [_batteryUpdated:protected] =>      [_changed:protected] => 1 )
[2020-03-23 19:00:24][ERROR] : Erreur exécution de la commande [Ecl. Périphériques][Multi Salon][Refresh] : Le nom de l'équipement ne peut pas être vide : MerossIOT Object (     [id:protected] =>      [name:protected] =>      [logicalId:protected] =>      [generic_type:protected] =>      [object_id:protected] =>      [eqType_name:protected] => MerossIOT     [eqReal_id:protected] =>      [isVisible:protected] => 0     [isEnable:protected] => 0     [configuration:protected] => Array         (             [online] => 0         )      [timeout:protected] => 0     [category:protected] =>      [display:protected] =>      [order:protected] => 9999     [comment:protected] =>      [tags:protected] =>      [_debug:protected] =>      [_object:protected] =>      [_needRefreshWidget:protected] =>      [_timeoutUpdated:protected] =>      [_batteryUpdated:protected] =>      [_changed:protected] => 1 )
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 126, in execute_command
return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/client.py", line 302, in execute_cmd
raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
----------------------------------------
----------------------------------------
Exception happened during processing of request from
Traceback (most recent call last):
File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
self.handle()
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 104, in handle
response['result'] = response['result'](*args)
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 287, in syncDevice
d = self.syncOneMeross(device)
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 168, in syncOneMeross
data = device.get_sys_data()
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 129, in get_sys_data
return self.execute_command("GET", ALL, {})
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 126, in execute_command
return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/client.py", line 302, in execute_cmd
raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
----------------------------------------
----------------------------------------
Exception happened during processing of request from
Traceback (most recent call last):
File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
self.handle()
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 104, in handle
response['result'] = response['result'](*args)
File "/var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py", line 114, in setOn
res = device.turn_on_channel(int(channel))
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/devices/power_plugs.py", line 158, in turn_on_channel
return self._channel_control_impl(c, 1, callback=callback)
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/devices/power_plugs.py", line 35, in _channel_control_impl
return self._togglex(channel, status, callback=callback)
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/devices/power_plugs.py", line 29, in _togglex
return self.execute_command("SET", TOGGLEX, payload, callback=callback)
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py", line 126, in execute_command
return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
File "/usr/local/lib/python3.7/dist-packages/meross_iot/cloud/client.py", line 302, in execute_cmd
raise CommandTimeoutException("A timeout occurred while waiting for the ACK: %d" % timeout)
meross_iot.cloud.exceptions.CommandTimeoutException.CommandTimeoutException: A timeout occurred while waiting for the ACK: 10
----------------------------------------
```

Patrice

**Comment by Jeremie-C** [comment]
Confirmé.
Il apparaît que le démon se déconnecte et provoque l'erreur.
Je vais tenter un gestion d'événements qui reconnecte automatiquement.
Merci pour le signalement.

**Comment by StephaneG38** [comment]
Hello @Jeremie-C 
J'ai également des problèmes avec le plugin sur 2 prises Meross mss310 avec un fonctionnement aléatoire sous la V4 + buster (RPI3).
L’application Meross fonctionne très bien sur mon téléphone android.
Si je redémarre le Démon cela fonctionne un moment.
Mais au bout de quelques heures cela ne fonctionne plus et impossible d’allumer ou d’éteindre ma lampe.
Merci par avance pour votre aide !
Stéphane

**Comment by Jeremie-C** [comment]
Bonsoir.
Bien reçu.
J'ai le même problème chez moi et je travaille dessus, mais j'ai peu de
temps en ce moment.
Je vous tient au courant des que possible.

**Comment by StephaneG38** [comment]
OK Merci !

**Comment by StephaneG38** [comment]
Hello,
Depuis dernière mise à jour du plugin cela fonctionne !!
Grand merci !!
Stéphane
